### PR TITLE
Fixed bug which allowed non-staff to give points to other users.

### PR DESCRIPTION
**Pull request by brysonmco**
Added a return statement, may want to do an LB reset

### CODE REVIEW

**Comment by thesamgordon** [comment]
i am a good member of this discord server undeserving of a points reset, all 34 billion of my points have been earned.

**Comment by JoshCantCode** [comment]
My 6700 points were rightfully earned 🙏

**Comment by matytyma** [comment]
I just realized I didn't make a PR for this and made just #33 cause I committed it all to the main branch...

**Review by matytyma — CHANGES_REQUESTED** [review]
You should also add a return to [this if statement](https://github.com/Cortex-Development/cortex-bot/pull/34/files#diff-952951d66b93195a12a04e4f770cbc06f4e25dc0736f91cdabdf24dd6b384a8fR70-R72) to prevent storing a user that's not on the Discord server to the database

**Pull request closed without merging**
