### PR TITLE
Ephemeral messages

### PR DESCRIPTION
**Pull request by ampersanded-dev**
#### Other small changes:
* `.forceGuildOnly("503656531665879063")` changed to `.forceGuildOnly(discordConfiguration.getGuildId())`
* Changed text on line 96 of `ThankCommand.java` from second person to third person.

### CODE REVIEW

**Review by Scyye — APPROVED** [review]
Works fine

**Review by matytyma — APPROVED** [review]
Everything works well.

**Review by AwesomeBFM — APPROVED** [review]
Looks good, it looks like on line 96 of ThankCommand.java you changed the response from second person to third person, presumably for others reading it. This is a good change but I recommend that you make sure that you include all changes you make, even small ones like this, in your comment. Otherwise, everything appears to work well!

**Review by KodySimpson — APPROVED** [review]
Great work! Thank you

**Pull request merged**
